const NOTIFICATION_ROLE_MAP = {
  PO_CREATED:            ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER'],
  PO_UPDATED:            ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER'],
  PO_AMENDED:            ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER'],
  PO_CANCELLED:          ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER'],
  PO_STATUS_CHANGED:     ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER'],
  GRN_SUBMITTED:         ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER','LAB_ASSISTANT'],
  LAB_RM_APPROVED:       ['MAIN_MASTER','SUPERVISOR','MATERIALS_RECEIVER','PRODUCTION_STAFF'],
  LAB_RM_REJECTED:       ['MAIN_MASTER','SUPERVISOR','MATERIALS_RECEIVER'],
  LAB_RM_RESAMPLE:       ['MAIN_MASTER','SUPERVISOR','MATERIALS_RECEIVER'],
  FINAL_QTY_SUBMITTED:   ['MAIN_MASTER','SUPERVISOR','PRODUCTION_STAFF'],
  PRODUCTION_STARTED:    ['MAIN_MASTER','SUPERVISOR','LAB_ASSISTANT','PRODUCTION_STAFF'],
  PRODUCTION_ON_HOLD:    ['MAIN_MASTER','SUPERVISOR','PRODUCTION_STAFF'],
  PRODUCTION_COMPLETED:  ['MAIN_MASTER','SUPERVISOR','LAB_ASSISTANT','PRODUCTION_STAFF'],
  PRODUCTION_QC_PASSED:  ['MAIN_MASTER','SUPERVISOR','PRODUCTION_STAFF','SALES_TEAM'],
  PRODUCTION_QC_FAILED:  ['MAIN_MASTER','SUPERVISOR','PRODUCTION_STAFF'],
  STOCK_LOW_ALERT:       ['MAIN_MASTER','SUPERVISOR','SALES_TEAM'],
  RM_LOW_STOCK_ALERT:    ['MAIN_MASTER','SUPERVISOR','PURCHASE_ACCOUNTANT','MATERIALS_RECEIVER'],
  STOCK_EXPIRY_ALERT:    ['MAIN_MASTER','SUPERVISOR','SALES_TEAM'],
  STOCK_CRITICAL:        ['MAIN_MASTER','SUPERVISOR','SALES_TEAM'],
  STOCK_REPRODUCTION:    ['MAIN_MASTER','SUPERVISOR','PRODUCTION_STAFF'],
  ASSET_PR_CREATED:      ['MAIN_MASTER','SUPERVISOR'],
  ASSET_PR_APPROVED:     ['MAIN_MASTER','SUPERVISOR'],
  ASSET_PQ_CREATED:      ['MAIN_MASTER','SUPERVISOR'],
  ASSET_PO_CREATED:      ['MAIN_MASTER','SUPERVISOR'],
  ASSET_GRPO_CREATED:    ['MAIN_MASTER','SUPERVISOR'],
  ASSET_INVOICE_CREATED: ['MAIN_MASTER','SUPERVISOR'],
  ASSET_INVOICE_PAID:    ['MAIN_MASTER','SUPERVISOR'],
  ASSET_DECOMMISSIONED:  ['MAIN_MASTER','SUPERVISOR'],
  UPCOMING_DELIVERY:     ['MAIN_MASTER','SUPERVISOR','MATERIALS_RECEIVER'],
};

const isVisibleToRole = (type, role) => NOTIFICATION_ROLE_MAP[type]?.includes(role) ?? false;

module.exports = {
  NOTIFICATION_ROLE_MAP,
  isVisibleToRole
};
